import React, { useState } from 'react';
import { GeneratedArt } from '../types';
import { DownloadIcon } from './Icons';

interface ArtFrameProps {
  art: GeneratedArt | null;
  isLoading: boolean;
  loadingMessage: string;
}

const ArtFrame: React.FC<ArtFrameProps> = ({ art, isLoading, loadingMessage }) => {
  const [isHovered, setIsHovered] = useState(false);
  // Add a nice museum-style loading state
  if (isLoading) {
    return (
      <div className="w-full h-full flex items-center justify-center bg-neutral-900 border border-neutral-800 shadow-2xl relative overflow-hidden group">
         {/* Subtle pattern background */}
         <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
         <div className="z-10 flex flex-col items-center">
            <div className="w-12 h-12 border-4 border-amber-700/50 border-t-amber-500 rounded-full animate-spin mb-4"></div>
            <span className="text-amber-100 font-serif tracking-widest text-sm">{loadingMessage}</span>
         </div>
      </div>
    );
  }

  if (!art) {
    return (
      <div className="w-full h-full flex items-center justify-center bg-neutral-900 border border-neutral-800 shadow-inner">
        <p className="text-neutral-500 font-serif italic text-xl">Select a style to commission a masterpiece.</p>
      </div>
    );
  }

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = art.url;
    link.download = `heritage-art-${art.style.replace(/\s/g, '-').toLowerCase()}-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div 
      className="relative w-full h-full flex flex-col items-center justify-center p-4 md:p-8 perspective-1000"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* The Physical Frame */}
      <div className="relative bg-[#1a1a1a] p-3 md:p-6 shadow-[0_20px_50px_rgba(0,0,0,0.7)] rounded-sm border border-[#333]">
        
        {/* Inner Matte */}
        <div className="bg-[#e5e5e5] p-2 md:p-8 shadow-inner">
           
           {/* The Artwork Canvas */}
           <div className="relative overflow-hidden bg-white">
             <img 
               src={art.url} 
               alt={art.style} 
               className="max-h-[60vh] md:max-h-[65vh] object-contain w-auto block mx-auto"
             />
             
             {/* Signature/Label Overlay */}
             <div className="absolute bottom-4 right-4 bg-white/90 backdrop-blur-sm px-3 py-1 text-xs font-serif text-black border border-gray-200 opacity-70">
                Generated by Gemini • {art.style}
             </div>
           </div>
        </div>

        {/* Spotlights effects (simulated) */}
        <div className="absolute top-0 left-0 right-0 h-32 bg-gradient-to-b from-white/5 to-transparent pointer-events-none"></div>
      </div>

      {/* Caption Card */}
      <div className="mt-8 bg-neutral-900/80 backdrop-blur border border-neutral-700 px-6 py-4 rounded text-center max-w-lg">
         <h2 className="text-xl md:text-2xl text-amber-500 font-serif mb-1">{art.style}</h2>
         <p className="text-neutral-400 text-sm">
           Created {new Date(art.timestamp).toLocaleTimeString()}
         </p>
         
         {/* Action Button */}
         <button 
           onClick={handleDownload}
           className="mt-4 flex items-center justify-center mx-auto space-x-2 text-xs uppercase tracking-wider text-neutral-300 hover:text-white transition-colors"
         >
           <DownloadIcon className="w-4 h-4" />
           <span>Download High-Res</span>
         </button>
      </div>
    </div>
  );
};

export default ArtFrame;